/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AideRouteImport } from './routes/aide'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FichesRouteImport } from './routes/fiches'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AideRoute = AideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FichesRoute = FichesRouteImport.update({
  id: '/fiches',
  path: '/fiches',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aide': typeof AideRoute
  '/contact': typeof ContactRoute
  '/fiches': typeof FichesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aide': typeof AideRoute
  '/contact': typeof ContactRoute
  '/fiches': typeof FichesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aide': typeof AideRoute
  '/contact': typeof ContactRoute
  '/fiches': typeof FichesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aide' | '/contact' | '/fiches'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aide' | '/contact' | '/fiches'
  id: '__root__' | '/' | '/aide' | '/contact' | '/fiches'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AideRoute: typeof AideRoute
  ContactRoute: typeof ContactRoute
  FichesRoute: typeof FichesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide': {
      id: '/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof AideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiches': {
      id: '/fiches'
      path: '/fiches'
      fullPath: '/fiches'
      preLoaderRoute: typeof FichesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AideRoute: AideRoute,
  ContactRoute: ContactRoute,
  FichesRoute: FichesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
